# Generated by Django 6.0.8 on 2026-08-06 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('dev', 'Developer'), ('tl', 'Team Lead'), ('guest', 'Guest')], default='guest', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('pub_key', models.TextField()),
                ('join_timestamp', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='users', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeactivationLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_log', to='users.user')),
            ],
        ),
    ]
