# Generated by Django 5.2.17 on 2026-09-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dev', 'Developer'), ('tl', 'Team Lead')], default='dev', max_length=20),
        ),
    ]
