# Generated by Django 5.2.17 on 2026-09-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
