services:
  database:
    ports:
      - "5432:5432"

  backend:
    ports:
      - "8000:8000"
    volumes:
      - ./secure-vault-backend:/app # bind mount for backend source code to enable live code reloading

  frontend:
    ports:
      - "5173:5173"

  # Optional: pgAdmin for database management and visualization
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: secure-vault-db-console
    env_file:
      - ./database/pgadmin/.env
    ports:
      - "5431:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - secure-vault-network
    depends_on:
      - database
    restart: unless-stopped
    profiles:
      - debugging

  # Optional: Database migration service to handle schema changes and migrations
  db_migration:
    build:
      context: ./secure-vault-backend
      dockerfile: ./database-migration/Dockerfile
    image: secure-vault-db-migration:local
    container_name: secure-vault-db-migration
    working_dir: /app
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    env_file:
      - ./database/database-migration/.env
      - ./database/.env
    volumes:
      - ./secure-vault-backend:/app
      - ./database/scripts/postgres_pre_migrate_init.sql:/db-scripts/postgres_pre_migrate_init.sql:ro
      - ./database/scripts/postgres_post_migrate_init.sql:/db-scripts/postgres_post_migrate_init.sql:ro
    command: >
      sh -c "
      PGPASSWORD=$$POSTGRES_PASSWORD psql -h database -U postgres -d postgres -v ON_ERROR_STOP=1 -v db_name=$$DB_NAME -v db_user=$$DB_MIGRATION_USER -v db_user_password=$$DB_MIGRATION_USER_PASSWORD -v app_user=$$DB_USER -f /db-scripts/postgres_pre_migrate_init.sql &&
      DB_USER=$$DB_MIGRATION_USER DB_PASSWORD=$$DB_MIGRATION_USER_PASSWORD python manage.py migrate --noinput &&
      PGPASSWORD=$$POSTGRES_PASSWORD psql -h database -U postgres -d $$DB_NAME -v ON_ERROR_STOP=1 -v db_name=$$DB_NAME -v db_user=$$DB_USER -v db_user_password=$$DB_USER_PASSWORD -f /db-scripts/postgres_post_migrate_init.sql
      "
    depends_on:
      database:
        condition: service_healthy
    networks:
      - secure-vault-network
    restart: "no"
    profiles:
      - migration
