services:
  database:
    image: postgres:16-alpine
    container_name: secure-vault-db
    env_file:
      - ./database/.env
    volumes:
      # PostgreSQL data persistence
      - postgres_data:/var/lib/postgresql/data
    networks:
      - secure-vault-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./secure-vault-backend
      dockerfile: Dockerfile
    image: secure-vault-backend:local
    container_name: secure-vault-backend
    # Optionally override the default command to run the Django server
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./secure-vault-backend/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - secure-vault-network
    restart: unless-stopped

  frontend:
    build:
      context: ./secure-vault-frontend
      dockerfile: Dockerfile
    image: secure-vault-frontend:local
    container_name: secure-vault-frontend
    volumes:
      - ./secure-vault-frontend:/app
      - /app/node_modules
    env_file:
      - ./secure-vault-frontend/.env
    depends_on:
      - backend
    networks:
      - secure-vault-network
    restart: unless-stopped

  proxy:
    image: nginx:1.27-alpine
    container_name: secure-vault-nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./nginx/.env
    volumes:
      - ./nginx/dev.conf:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - secure-vault-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  secure-vault-network:
    driver: bridge
