# Generated by Django 6.0.8 on 2026-08-14 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('password', 'Password'), ('api_key', 'API Key'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('value', models.BinaryField()),
                ('marker', models.CharField(blank=True, max_length=256, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='HoneypotSecretAccessLog',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_secrets.secret')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sharing_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sharing_revoked', models.BooleanField(default=False)),
                ('sharing_content_id', models.CharField(max_length=256)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_instances', to='user_secrets.secret')),
                ('sharing_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_secrets', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SharedSecretAccessLog',
            fields=[
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_secrets.sharedsecret')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
