# Generated by Django 5.2.17 on 2026-09-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='iv',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
