# Generated by Django 6.0.8 on 2026-08-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='sharable',
        ),
    ]
