# Generated by Django 5.2.17 on 2026-09-07 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0002_secret_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedsecret',
            name='sharing_content_id',
        ),
    ]
