# Generated by Django 5.2.17 on 2026-09-09 18:53

import django.db.models.deletion
from django.db import migrations, models


def copy_logged_shared_secret_ids(apps, schema_editor):
    SharedSecret = apps.get_model('user_secrets', 'SharedSecret')
    SharedSecretAccessLog = apps.get_model('user_secrets', 'SharedSecretAccessLog')

    shared_secret_to_secret = dict(
        SharedSecret.objects.values_list('id', 'secret_id')
    )

    for access_log in SharedSecretAccessLog.objects.all().only('id', 'secret_id'):
        mapped_secret_id = shared_secret_to_secret.get(access_log.secret_id)
        if mapped_secret_id is None:
            access_log.secret_temp_id = None
        else:
            access_log.secret_temp_id = mapped_secret_id
        access_log.save(update_fields=['secret_temp'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0003_remove_sharedsecret_sharing_content_id'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedsecretaccesslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='sharedsecretaccesslog',
            name='secret_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_secrets.secret'),
        ),
        migrations.RunPython(copy_logged_shared_secret_ids, noop_reverse),
        migrations.RemoveField(
            model_name='sharedsecretaccesslog',
            name='secret',
        ),
        migrations.RenameField(
            model_name='sharedsecretaccesslog',
            old_name='secret_temp',
            new_name='secret',
        ),
    ]
