# Generated by Django 5.2.17 on 2026-09-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0004_sharedsecretaccesslog_user_and_more'),
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedSecretAccessLog',
            new_name='SecretAccessLog',
        ),
    ]
