# Generated by Django 5.2.17 on 2026-09-20 22:17

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0005_rename_sharedsecretaccesslog_secretaccesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLedgerState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_block_index', models.PositiveBigIntegerField(default=0)),
                ('last_block_hash', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'audit ledger state',
                'verbose_name_plural': 'audit ledger state',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_id', models.UUIDField(blank=True, null=True)),
                ('secret_type', models.CharField(blank=True, max_length=20, null=True)),
                ('secret_label', models.CharField(blank=True, max_length=100, null=True)),
                ('is_shared_secret', models.BooleanField(default=False)),
                ('is_honeypot_secret', models.BooleanField(default=False)),
                ('owner_id', models.UUIDField(blank=True, null=True)),
                ('owner_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=64)),
                ('block_index', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('previous_hash', models.CharField(max_length=64)),
                ('block_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.CharField(blank=True, max_length=2048, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='secretaccesslog',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='secretaccesslog',
            name='user',
        ),
        migrations.DeleteModel(
            name='HoneypotSecretAccessLog',
        ),
        migrations.DeleteModel(
            name='SecretAccessLog',
        ),
    ]
