# Generated by Django 5.2.17 on 2026-09-22 20:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_secrets', '0006_auditledgerstate_auditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='last_rotated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
